# Copyright 2021 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-please-main

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3.7
        id: release-please
        with:
          release-type: go
          package-name: devenv.sh-action
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          changelog-notes-type: github

      - if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v4

      - name: tag major version
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/mesosphere/mindthegap-action.git"
          git tag -fa v${{ steps.release-please.outputs.major }} -m "Release v${{ steps.release-please.outputs.major }}"
          git push -f origin v${{ steps.release-please.outputs.major }}

